[env:nodemcuv2]
platform = espressif8266
board = nodemcuv2
framework = arduino

lib_deps = 
    adafruit/RTClib
    https://github.com/marvinroger/arduino-liquidcrystal-rtm.git
    bblanchon/ArduinoJson